<?php
namespace grozzzny\partners;

use Yii;
use yii\easyii2\components\FastModule;

class PartnersModule extends FastModule
{
    public $settings = [
        'modelPartners' => '\grozzzny\partners\models\Partners',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::registerTranslation();
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['app/partners'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/partners/messages',
            'fileMap' => [
                'app/partners' => 'partners.php',
            ],
        ];
    }

    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return Yii::t('app/partners', 'Partners');
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->id;
    }

    public function getIcon()
    {
        // TODO: Implement getIcon() method.
        return 'file';
    }
}